name: Bismillah
description: An Islamic Prayer time application.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  adhan: ^1.1.14
  shared_preferences: ^0.5.2
  flutter_neumorphic: ^3.0.3
  location: ^3.0.2
  intl: ^0.16.1
  buy_me_a_coffee_widget: ^1.0.1
  geocoder: ^0.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
  flutter_native_splash: ^0.1.9
  flutter_launcher_name: "^0.0.1"
  
flutter_launcher_name:
  name: "Prayer Time"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"

flutter_native_splash:
  image: images/logo.png
  color: "000000"
  fill: false
  android_disable_fullscreen: false

flutter:

   uses-material-design: true
   assets:
      - images/bottom_bg.png
      - images/top_bg.png

   fonts:
     - family: Bismillah
       fonts:
         - asset: fonts/Bismillahscript.ttf
  
