name: Bismillah
description: An Islamic Prayer time application.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  adhan: ^1.1.14
  shared_preferences: ^0.5.2
  flutter_neumorphic: ^3.0.3
  location: ^3.0.2
  intl: ^0.16.1
  geocoder: ^0.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

   uses-material-design: true
   assets:
      - images/bottom_bg.png
      - images/top_bg.png

   fonts:
     - family: Bismillah
       fonts:
         - asset: fonts/Bismillahscript.ttf
  
